[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    # time
    "RUSTSEC-2020-0071",
]

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "Unicode-DFS-2016"]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = []
skip-tree = [
    # sentry-types depends on both time 0.3 and chrono -> time 0.1
    { name = "time", version = "=0.1.44" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[sources.allow-org]
github = ["EmbarkStudios"]
